<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Infrastructure\" />
    <Folder Include="Views\Profile\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.2" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RFQ.UI.Application\RFQ.UI.Application.csproj" />
    <ProjectReference Include="..\RFQ.UI.Infrastructure\RFQ.UI.Infrastructure.csproj" />
  </ItemGroup>

</Project>
